Controllers/TeacherHomepageController.cs
using LearningManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LearningManagementSystem.Controllers
{
    [Authorize]
    public class TeacherHomepageController : Controller
    {
        // GET: TeacherHomepage
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CourseToTeach()
        {
            DbmsProjectEntities1 db = new DbmsProjectEntities1();

            List<Teacher> tea = db.Teachers.ToList();
            List<registraton> reg = db.registratons.ToList();
            var mutliclass = from t in tea join r in reg on t.Tid equals r.Tid
                             into table1 from r in table1.ToList()
                             select new Multiclass { Teacher = t, Registraton=r };
            Console.WriteLine(mutliclass);
            return View(mutliclass);
            
        }

    }
}

Views/TeacherHomepage/CourseToTeach.cshtml
@model IEnumerable<LearningManagementSystem.Models.Multiclass>


@{
    ViewBag.Title = "Index";
}
<style>


    body {
        color: white;
        margin-top: 20px;
        background-color: #091b1a;
        font-family: "Roboto", sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
</style>
<h1>Course You want To Teach</h1>
<table class="table">
    <tr>
        <td>
            CourseId
        </td>
        <td>
            Course Name
        </td>
        <td>
            CreditHours
        </td>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@item.Registraton.cours.Cid</td>
    <td>@item.Registraton.cours.Cname</td>
    <td>@item.Registraton.cours.CreditHours</td>

</tr>
    }
</table>

<div style="background-color:black;margin-top:10px; width:12%;padding:8px;margin-left:10px;text-align:center">
    <a>@Html.ActionLink("Back To main", "Index", "TeacherHomepage")</a>
</div>

Views/TeacherHomepage/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<style>


    body {
        color: white;
        margin-top: 20px;
        background-color: #091b1a;
        font-family: "Roboto", sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
</style>
<div style="background-color:black;margin-top:10px; width:12%;padding:8px;margin-left:10px;text-align:center">

    <a>@Html.ActionLink("ViewCourses To Teach", "CourseToTeach", "TeacherHomepage")</a>
</div>