Controllers/StudentsHomepageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LearningManagementSystem.Models;

namespace LearningManagementSystem.Controllers
{
    public class StudentsHomepageController : Controller
    {
        [Authorize]
        // GET: StudentsHomepage
        public ActionResult Index()
        {

            return View();
        }
        public ActionResult Details()
        {
            DbmsProjectEntities1 db = new DbmsProjectEntities1();

            List<Student> std = db.Students.ToList();
            List<registraton> reg = db.registratons.ToList();
            var mutliclass = from s in std
                             join r in reg on s.stdid equals r.stdid
                             into table1
                             from r in table1.ToList()
                             select new Multiclass { Student = s, Registraton = r };
            Console.WriteLine(mutliclass);
            return View(mutliclass);
        }
    }
}

Views/StudentsHomepage/Details.cshtml
@model IEnumerable<LearningManagementSystem.Models.Multiclass>


@{
    ViewBag.Title = "Index";
}
<style>


    body {
        color: white;
        margin-top: 20px;
        background-color: #091b1a;
        font-family: "Roboto", sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
</style>
<h1>Details</h1>
<table class="table">
    <tr>
        <td>
            CourseId
        </td>
        <td>
            Course Name
        </td>
        <td>
            CreditHours
        </td>
        <td>
            Teacherid
        </td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Registraton.Regid</td>
            <td>@item.Registraton.Cid</td>
            <td>@item.Registraton.cours.Cname</td>
            <td>@item.Registraton.Tid</td>

        </tr>
    }
</table>
<div style="background-color:black;margin-top:10px; width:12%;padding:8px;margin-left:10px;text-align:center">
    <a>@Html.ActionLink("Back To main", "Index", "StudentsHomepage")</a>
</div>

Views/StudentsHomepage/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<style>


    body {
        color: white;
        margin-top: 20px;
        background-color: #091b1a;
        font-family: "Roboto", sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
</style>
<div style="background-color:black;margin-top:10px; width:12%;padding:8px;margin-left:10px;text-align:center">
    <a>@Html.ActionLink("Detials", "Details", "StudentsHomepage")</a>
</div>